# Generated by Django 2.1.7 on 2019-03-30 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='楽器の名前')),
                ('type', models.CharField(choices=[('ギター', 'ギター'), ('ギター', 'ベース')], default='ギター', max_length=10, verbose_name='楽器の種類')),
                ('brand', models.CharField(max_length=128, verbose_name='ブランド名')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
