# Generated by Django 2.1.7 on 2019-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='楽器の名前')),
                ('type', models.CharField(choices=[('guitar', 'ギター'), ('bass', 'ベース')], default='guitar', max_length=10, verbose_name='楽器の種類')),
                ('brand', models.CharField(max_length=128, verbose_name='ブランド名')),
            ],
        ),
    ]
