# Generated by Django 2.1.7 on 2019-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='楽器の名前')),
                ('type', models.CharField(choices=[('ギター', 'ギター'), ('ギター', 'ベース')], default='ギター', max_length=10, verbose_name='楽器の種類')),
                ('brand', models.CharField(max_length=128, verbose_name='ブランド名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='楽器の画像')),
            ],
        ),
    ]
