# Generated by Django 2.1 on 2019-02-16 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='エフェクターの名前')),
                ('type', models.CharField(choices=[('stomp_box', 'コンパクトエフェクター'), ('multi_effects', 'マルチエフェクター')], max_length=128, verbose_name='エフェクターの種類')),
                ('effect', models.CharField(choices=[('overdrive', 'オーバードライブ'), ('distortion', 'ディストーション'), ('fuzz', 'ファズ'), ('reverb', 'リバーブ'), ('delay', 'ディレイ'), ('chorus', 'コーラス'), ('phaser', 'フェイザー'), ('flanger', 'フランジャー'), ('wah', 'ワウ'), ('pitch shifter', 'ピッチシフター'), ('others', 'その他')], max_length=128, verbose_name='エフェクト名')),
                ('brand', models.CharField(max_length=128, verbose_name='ブランド名')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
