# Generated by Django 2.2 on 2019-04-13 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
