# Generated by Django 2.1.7 on 2019-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedal',
            name='type',
            field=models.CharField(choices=[('stomp_box', 'コンパクトエフェクター'), ('multi_effects', 'マルチエフェクター')], default='stomp_box', max_length=128, verbose_name='エフェクターの種類'),
        ),
    ]
