# Generated by Django 2.1.7 on 2019-03-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='follow',
            new_name='followee',
        ),
    ]
