# Generated by Django 2.1 on 2019-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_favorite_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_tone',
            field=models.ManyToManyField(blank=True, related_name='fav_by', to='tones.Tone', verbose_name='お気に入りのプリセット'),
        ),
    ]
