# Generated by Django 2.1.7 on 2019-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190329_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='follower',
        ),
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
