# Generated by Django 2.1.7 on 2019-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amps', '0001_initial'),
        ('instruments', '0001_initial'),
        ('pedals', '0002_auto_20190321_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='プリセット名')),
                ('amp', models.ManyToManyField(blank=True, to='amps.Amp')),
                ('instrument', models.ManyToManyField(blank=True, to='instruments.Instrument')),
                ('pedal', models.ManyToManyField(blank=True, to='pedals.Pedal')),
            ],
        ),
    ]
