# Generated by Django 2.1.7 on 2019-04-10 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tones', '0001_initial'),
        ('instruments', '0002_instrument_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tone',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tone',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument'),
        ),
    ]
