# Generated by Django 2.2a1 on 2019-04-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tones', '0002_auto_20190411_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tone',
            old_name='tone_info',
            new_name='info',
        ),
    ]
