# Generated by Django 2.2 on 2019-04-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190413_1449'),
        ('tones', '0004_auto_20190413_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('tone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tones.Tone')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tones.Comment')),
                ('tone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tones.Tone')),
            ],
        ),
    ]
