# Generated by Django 2.2 on 2019-05-10 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tones', '0006_tone_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tone',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3', 'aac', 'mp4'])]),
        ),
    ]
